"""
Django settings for ECS_GUI project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$9c=nlz+&16&m*m6ao!ow2#z7y@*gixjqp2rh^v_*5u(gd=dwl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'guardian',
    'widget_tweaks',
    'GUI.apps.GuiConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'GUI.middleware.OneSessionPerUserMiddleware',
]

ROOT_URLCONF = 'ECS_GUI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'GUI.context_processors.template_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'ECS_GUI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_L10N = True

USE_TZ = True

#https stuff
#SECURE_SSL_REDIRECT = True
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

#PCA settings
#ping intervall in seconds
PINGINTERVAL = 2
#timeout for messages to PCA in ms
TIMEOUT = 2000
#timeout for Pings to PCA in ms
PINGTIMEOUT = 2000

#address and port for ECS
ECS_ADDRESS = "localhost"
ECA_REQUEST_PORT = 5000
ECA_LOG_PORT = 5001
ECS_PUBLISHPORT = 5002
ECS_GET_STATETABLE_PORT = 5003

#unmapped Detectors
UNUSED_DETECTORS_PUBLISH_PORT = 5002
UNUSED_DETECTORS_CURRENT_STATE_PORT = 5003
UNUSED_DETECTORS_UPDATES_PORT = 5004

PATH_TO_PROJECT = "/home/daniel/Dokumente/Masterarbeit/ECS"
PCA_CONFIG_PATH = PATH_TO_PROJECT+"/init.cfg"
PCA_CODEFILE_NAME = "PCA.py"
DETECTOR_CODEFILE_NAME = "DetectorController.py"
GLOBALSYSTEM_CODE_FILE = "GlobalSystemClient.py"
CHECK_IF_RUNNING_SCRIPT = "checkIfRunning.py"
LOG_PATH_ECS = "./logECS"
PYTHON_VIRTENV_ACTIVATE_FILE = "virtenv"
ECS_DATABASE = PATH_TO_PROJECT+"/Django/ECS_GUI/ECS_database.db"
START_CLIENTS = False

ENCRYPT_WEBSOCKET=False
SSL_CERT_FILE="/etc/apache2/ssl/crt/apache.crt"
SSL_PEM_FILE="/etc/apache2/ssl/key/apache.key"
WEB_SOCKET_PORT = 5678

# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # this is default
    'guardian.backends.ObjectPermissionBackend',
)
#in seconds
PERMISSION_TIMEOUT = 20*60

#number of send Log entrys on connect
BUFFERED_LOG_ENTRIES =  50
